# Generated by Django 4.2 on 2023-06-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_brand', to='ecommerce.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_color', to='ecommerce.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_four', to='ecommerce.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_size', to='ecommerce.productvariant'),
        ),
    ]
