# Generated by Django 4.2 on 2023-06-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_productvariantprice_product_variant_brand_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantprice',
            unique_together={('product_variant_size', 'product_variant_color', 'product_variant_brand', 'product_variant_four', 'product')},
        ),
    ]
