# Generated by Django 4.2 on 2023-06-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_productvariantprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariantprice',
            name='product_variant_warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_warranty', to='ecommerce.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantprice',
            unique_together={('product_variant_color', 'product_variant_color', 'product_variant_size', 'product_variant_size', 'product_variant_warranty', 'product_variant_warranty', 'product_variant_brand', 'product_variant_brand', 'product')},
        ),
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_four',
        ),
    ]
